image: registry.znuny.com/znuny/docker-otrs6ci:latest

services:
  - name: registry.znuny.com/znuny/docker-mysql-utf8:latest
    alias: mysql

variables:
  MYSQL_DATABASE: otrs
  MYSQL_ROOT_PASSWORD: znuny4otrs

stages:
  - test
  - deploy

job_unit_otrs_Znuny4OTRSGIArticleSend:
  stage: test
  script:
    - env
    - pwd
    - /run.sh
    - su -c "perl /opt/otrs/bin/otrs.Console.pl Znuny4OTRS::AdvancedPackageManager::InstallSOPM /opt/otrs/Znuny4OTRS-GIArticleSend.sopm" -s /bin/bash otrs
    - su -c "perl /opt/otrs/bin/otrs.Console.pl Dev::UnitTest::Run --verbose --test Znuny4OTRSGIArticleSend/GenericInterface/Operation/Ticket/TicketCreate" -s /bin/bash otrs
    - su -c "perl /opt/otrs/bin/otrs.Console.pl Dev::UnitTest::Run --verbose --test Znuny4OTRSGIArticleSend/GenericInterface/Operation/Ticket/TicketUpdate" -s /bin/bash otrs

job_deploy_otrs_Znuny4OTRSGIArticleSend:
  stage: deploy
  script:
    - sh /sync_repo.sh git@github.com:znuny/Znuny4OTRS-GIArticleSend.git

